using UnityEngine;
using UnityEngine.UI;
using TMPro;
using System.Collections;

/// <summary>
/// Displays the item icon, name, and reward value for the list of landmark rewards generated by
/// the cartographer's guild.
/// </summary>
public class DUILandmarkChart : MonoBehaviour {

    public Image itemIcon;
    public TextMeshProUGUI itemName;
    public TextMeshProUGUI rewardText;

    [Space]
    public ChartInfo chartInfo;

	// Use this for initialization
	public void Init(ChartInfo info)
    {
        chartInfo = info;

        itemIcon.sprite = info.chartItem.icon;
        itemName.text = info.chartItem.LocalizedName();
        rewardText.text = info.reward.ToString();
    }
}
